config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
   @book = Book.new
   @books = Book.all
  end


  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      #@book = Book.find(params[:id])
       @books = Book.all
       render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path
     else
      render :edit
    end
  end


  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<body>
    <h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book,local: true do |f| %>
 <h4>Title</h4>
 <%= f.text_field :title %>

 <h4>Body</h4>
 <%= f.text_area :body %>
 <br>
 <%= f.submit 'Update Book' %>

<% end %>


  <%= link_to 'Show', book_path %> |
  <%= link_to 'Back', books_path %>


</body>

app/views/books/index.html.erb
    <p id="notice"></p>

    <h1>Books</h1>

<table>
 <thead>
 <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
 </tr>
 </thead>


<tbody>
<% @books.each do |book| %>
<tr>

  <td><%= book.title %></td>
  <td><%= book.body %></td>

  <td><%= link_to 'Show', book_path(book) %></td>
  <td><%= link_to 'Edit', edit_book_path(book) %></td>
  <td><%= link_to 'Destroy', destroy_book_path(book), method: :delete %></td>

</tr>
  <% end %>
</tbody>
</table>


<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book ,local: true do |f| %>
 <h4>Title</h4>
 <%= f.text_field :title %>
 <h4>Body</h4>
 <%= f.text_area :body %>
 <br>
<%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
 <body>
    <p id="notice"></p>
   <%= notice %>

<p>
  <strong>Title:</strong>
  <td><%= @book.title %></td>
</p>

<p>
  <strong>Body:</strong>
  <td><%= @book.body %></td>
</p>


<%= link_to 'Edit', edit_book_path(@book.id) %> |
<%= link_to 'Back', books_path %>



</body>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      .turbolinks-progress-bar {
       position: fixed;
       display: block;
       top: 0;
       left: 0;
       height: 3px;
       background: #0076ff;
       z-index: 9999;
       transition: width 300ms ease-out, opacity 150ms 150ms ease-in;
       transform: translate3d(0, 0, 0);
     }
</style>
    <title>WebCampBackendNew</title>
    <meta name="csrf-param" content="authenticity_token">
    <meta name="csrf-token" content="Nj1eYPWxHG81QAONXGdWsFzISOTPwp6V1Q9nIh2ghv6PUgoWMTnO3PcBPNWzArZinjUWr3l5RqgCcaomd4nfmg==">
    <link rel="stylesheet" media="all" href="/assets/application-d12397cbc3a266ce5a99f7b588223090c55ca04a439953bb5f9304395de93fc3.css" data-turbolinks-track="reload">
    <script src="/assets/application-114264dd93c8ff30e4335b71eed7949d66c4e7a8eb62e2de6284c046fe07104b.js" data-turbolinks-track="reload"></script>
 </head>

 <body>
   <h1>
     ようこそ
     <strong>Bookers</strong>
     へ!
   </h1>
   <p>
     <strong>Bookers</strong>
     では、さまざまな書籍に関するあなたの意見や
   </p>
   <p>印象を共有し交換することができます</p>
     <p>
       <%= link_to 'start',  books_path %>
     </p>
 </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>